<?php
/**
 * Template for displaying single recipe
 *
 * @package RecipeMaster
 */

get_header();
?>

<div class="min-h-screen bg-gray-50">
    <div class="container mx-auto px-4 py-8 max-w-4xl">
        <div class="mb-8">
            <h1 class="text-3xl md:text-4xl font-bold mb-4 font-playfair tracking-wide"><?php the_title(); ?></h1>
            
            <!-- Recipe taxonomies -->
            <div class="flex flex-col gap-2 mb-4">
                <?php
                // Meal type taxonomy
                $meal_types = get_the_terms(get_the_ID(), 'meal_type');
                if ($meal_types && !is_wp_error($meal_types)) :
                ?>
                    <div class="flex items-center gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-tags h-5 w-5 text-purple-600">
                            <path d="m15 5 6.3 6.3a2.4 2.4 0 0 1 0 3.4L17 19"></path>
                            <path d="M9.586 5.586A2 2 0 0 0 8.172 5H3a1 1 0 0 0-1 1v5.172a2 2 0 0 0 .586 1.414L8.29 18.29a2.426 2.426 0 0 0 3.42 0l3.58-3.58a2.426 2.426 0 0 0 0-3.42z"></path>
                            <circle cx="6.5" cy="9.5" r=".5" fill="currentColor"></circle>
                        </svg>
                        <?php foreach ($meal_types as $meal_type) : ?>
                            <a href="<?php echo esc_url(get_term_link($meal_type)); ?>" class="inline-flex items-center border transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 bg-purple-600 text-white px-3 py-0.5 text-sm font-medium rounded-full hover:bg-purple-700">
                                <?php echo esc_html($meal_type->name); ?>
                            </a>
                        <?php endforeach; ?>
                    </div>
                    
                    <?php
                    // Recipe tags
                    $recipe_tags = get_the_terms(get_the_ID(), 'recipe_tag');
                    if ($recipe_tags && !is_wp_error($recipe_tags)) :
                    ?>
                        <div class="flex items-center gap-2 ml-7">
                            <div class="flex flex-wrap gap-2">
                                <?php foreach ($recipe_tags as $tag) : ?>
                                    <a href="<?php echo esc_url(get_term_link($tag)); ?>" class="inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 border-transparent bg-gray-100 text-gray-800 hover:bg-gray-200">
                                        #<?php echo esc_html($tag->name); ?>
                                    </a>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
            
            <!-- Featured image with overlay -->
            <?php if (has_post_thumbnail()) : ?>
                <div class="relative rounded-lg overflow-hidden h-[300px] md:h-[400px] mb-6">
                    <?php the_post_thumbnail('full', ['class' => 'w-full h-full object-cover']); ?>
                    <div class="absolute bottom-0 left-0 right-0 gradient-overlay p-4">
                        <div class="flex items-center gap-2">
                            <div class="flex items-center text-recipe-cream" data-rating="<?php echo esc_attr(get_field('rating') ?: '4.5'); ?>">
                                <div class="recipe-stars flex">
                                    <!-- Stars will be generated by JS -->
                                </div>
                                <span class="ml-2 font-medium text-recipe-cream">
                                    <?php echo esc_html(get_field('rating') ?: '4.5'); ?>
                                </span>
                                <span class="ml-1 text-sm text-recipe-cream">
                                    (<?php echo esc_html(get_field('review_count') ?: '0'); ?> <?php esc_html_e('reviews', 'recipe-master'); ?>)
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
            
            <!-- Recipe metadata grid -->
            <?php
            $prep_time = get_field('prep_time_minutes');
            $cook_time = get_field('cooking_time');
            $difficulty = get_field('difficulty_level');
            $servings = get_field('servings');
            $cuisine = get_field('cuisine');
            
            if ($prep_time || $cook_time || $difficulty || $servings || $cuisine) :
            ?>
            <div class="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
                <?php if ($cuisine) : ?>
                <div class="col-span-2 md:col-span-4 flex flex-col items-center p-3 bg-recipe-beige rounded-lg">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-globe h-6 w-6 text-recipe-red mb-1">
                        <circle cx="12" cy="12" r="10"></circle>
                        <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path>
                        <path d="M2 12h20"></path>
                    </svg>
                    <span class="text-sm text-gray-600"><?php esc_html_e('Cuisine', 'recipe-master'); ?></span>
                    <span class="font-medium"><?php echo esc_html($cuisine); ?></span>
                </div>
                <?php endif; ?>

                <?php if ($prep_time) : ?>
                <div class="flex flex-col items-center p-3 bg-recipe-beige rounded-lg">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-clock h-6 w-6 text-recipe-red mb-1">
                        <circle cx="12" cy="12" r="10"></circle>
                        <polyline points="12 6 12 12 16 14"></polyline>
                    </svg>
                    <span class="text-sm text-gray-600"><?php esc_html_e('Prep Time', 'recipe-master'); ?></span>
                    <span class="font-medium"><?php echo esc_html($prep_time); ?> <?php esc_html_e('mins', 'recipe-master'); ?></span>
                </div>
                <?php endif; ?>
                
                <?php if ($cook_time) : ?>
                <div class="flex flex-col items-center p-3 bg-recipe-beige rounded-lg">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-utensils h-6 w-6 text-recipe-red mb-1">
                        <path d="M3 2v7c0 1.1.9 2 2 2h4a2 2 0 0 0 2-2V2"></path>
                        <path d="M7 2v20"></path>
                        <path d="M21 15V2a5 5 0 0 0-5 5v6c0 1.1.9 2 2 2h3Zm0 0v7"></path>
                    </svg>
                    <span class="text-sm text-gray-600"><?php esc_html_e('Cook Time', 'recipe-master'); ?></span>
                    <span class="font-medium"><?php echo esc_html($cook_time); ?> <?php esc_html_e('mins', 'recipe-master'); ?></span>
                </div>
                <?php endif; ?>
                
                <?php if ($difficulty) : ?>
                <div class="flex flex-col items-center p-3 bg-recipe-beige rounded-lg">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-chef-hat h-6 w-6 text-recipe-red mb-1">
                        <path d="M17 21a1 1 0 0 0 1-1v-5.35c0-.457.316-.844.727-1.041a4 4 0 0 0-2.134-7.589a5 5 0 0 0-9.186 0a4 4 0 0 0-2.134 7.588c.411.198.727.585.727 1.041V20a1 1 0 0 0 1 1Z"></path>
                        <path d="M6 17h12"></path>
                    </svg>
                    <span class="text-sm text-gray-600"><?php esc_html_e('Difficulty', 'recipe-master'); ?></span>
                    <span class="font-medium"><?php echo esc_html(ucfirst($difficulty)); ?></span>
                </div>
                <?php endif; ?>
                
                <?php if ($servings) : ?>
                <div class="flex flex-col items-center p-3 bg-recipe-beige rounded-lg">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-recipe-red mb-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z"></path>
                    </svg>
                    <span class="text-sm text-gray-600"><?php esc_html_e('Servings', 'recipe-master'); ?></span>
                    <span class="font-medium"><?php echo esc_html($servings); ?></span>
                </div>
                <?php endif; ?>
            </div>
            <?php endif; ?>
        </div>
        
        <!-- Main recipe content -->
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
            <!-- Ingredients Section -->
            <div class="md:col-span-1">
                <div class="rounded-lg border text-card-foreground p-5 bg-white shadow-md mb-8">
                    <div class="flex items-center justify-between mb-4">
                        <h2 class="text-2xl font-bold"><?php esc_html_e('Ingredients', 'recipe-master'); ?></h2>
                    </div>
                    
                    <?php 
                    $calories = get_field('calories');
                    if ($servings || $calories) : 
                    ?>
                    <div class="flex items-center justify-between mb-4">
                        <?php if ($servings) : ?>
                        <p class="text-sm text-gray-600"><?php printf(esc_html__('For %d servings', 'recipe-master'), $servings); ?></p>
                        <?php endif; ?>
                        
                        <?php if ($calories) : ?>
                        <div class="inline-flex items-center px-3 py-1 rounded-full bg-gradient-to-r from-purple-500 to-pink-500 shadow-sm">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-badge w-4 h-4 text-white mr-1">
                                <path d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z"></path>
                            </svg>
                            <span class="text-xs font-semibold text-white"><?php echo esc_html($calories); ?> <?php esc_html_e('cal', 'recipe-master'); ?></span>
                        </div>
                        <?php endif; ?>
                    </div>
                    <?php endif; ?>
                    
                    <?php
                    $ingredients = get_field('ingredients');
                    if ($ingredients) :
                    ?>
                    <ul class="space-y-3">
                        <?php foreach ($ingredients as $ingredient) : ?>
                        <li class="flex items-start gap-2 p-2 hover:bg-gray-50 rounded-md transition-colors">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-check-big w-5 h-5 text-recipe-green mt-0.5 flex-shrink-0">
                                <path d="M21.801 10A10 10 0 1 1 17 3.335"></path>
                                <path d="m9 11 3 3L22 4"></path>
                            </svg>
                            <span>
                            <?php
                            $ingredient_text = $ingredient['name'];
                            if (!empty($ingredient['amount'])) {
                                $ingredient_text = $ingredient['amount'];
                                if (!empty($ingredient['unit'])) {
                                    $ingredient_text .= ' ' . $ingredient['unit'];
                                }
                                $ingredient_text .= ' ' . $ingredient['name'];
                            }
                            echo esc_html($ingredient_text);
                            ?>
                            </span>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                    <?php endif; ?>
                </div>
            </div>
            
            <!-- Instructions Section -->
            <div class="md:col-span-2">
                <div class="rounded-lg border text-card-foreground p-5 bg-white shadow-md mb-8">
                    <h2 class="text-2xl font-bold mb-4"><?php esc_html_e('Instructions', 'recipe-master'); ?></h2>
                    
                    <?php
                    $instructions = get_field('instructions');
                    if ($instructions) :
                    ?>
                    <ol class="space-y-6">
                        <?php foreach ($instructions as $index => $instruction) : ?>
                        <li class="flex">
                            <div class="flex-shrink-0 mr-4">
                                <div class="flex items-center justify-center w-8 h-8 bg-recipe-red text-white rounded-full">
                                    <?php echo esc_html($index + 1); ?>
                                </div>
                            </div>
                            <div class="pt-1">
                                <p class="text-gray-700"><?php echo wp_kses_post($instruction['step']); ?></p>
                                
                                <?php if (!empty($instruction['image'])) : ?>
                                <div class="mt-3 rounded-lg overflow-hidden">
                                    <?php echo wp_get_attachment_image($instruction['image'], 'medium', false, ['class' => 'w-full rounded-lg']); ?>
                                </div>
                                <?php endif; ?>
                            </div>
                        </li>
                        <?php endforeach; ?>
                    </ol>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        
        <?php
        $tips = get_field('tips');
        
        if ($tips) : 
        ?>
        <div data-orientation="horizontal" role="none" class="shrink-0 bg-border h-[1px] w-full my-6"></div>
        
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
            <?php if ($tips) : ?>
            <div class="md:col-span-3">
                <div class="rounded-lg border text-card-foreground p-5 bg-white shadow-md">
                    <h2 class="text-2xl font-bold mb-4"><?php esc_html_e('Tips & Notes', 'recipe-master'); ?></h2>
                    <div class="prose"><?php echo wp_kses_post($tips); ?></div>
                </div>
            </div>
            <?php endif; ?>
        </div>
        <?php endif; ?>
    </div>
</div>

<?php
get_footer();